### ISSUE TITLE
CalledProcessError not defined in _stop

### ISSUE THREAD

**Issue by lbeltrame** [roryk/ipython-cluster-helper#50]
Saw this when running bcbio (probably a missing import?):

```python
[2017-05-26T07:12Z] kyoko: Did not stop IPython cluster correctly
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 92, in stop
    ipython_cluster.stop_from_view(view)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 896, in stop_from_view
    _stop(view.clusterhelper["profile"], view.clusterhelper["cluster_id"])
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 904, in _stop
    except CalledProcessError:
NameError: global name 'CalledProcessError' is not defined
```

**Comment by chapmanb** [comment]
Luca;
Thanks for the report. This should have been fixed as of the 0.5.4 release:

https://github.com/roryk/ipython-cluster-helper/commit/445cdb30041617b2c52561394fc8fd4b2e5ad1a5#diff-48e74b7da82ef48a7f10cb19ef9edb56

Hopefully upgrading gets the expected behavior for you. Thanks again.
